exec/make_app_from_files.R
I've encountered a problem with this script with example data in an [nf-core module](https://github.com/nf-core/modules/pull/2315/), after adding an additional identifier column to the contrasts file. The script here makes assumptions about the column index (rather than name) used in contrast files). This PR switches the assumptions to column names instead.
=> Don't make assumptions about column numbers in contrast files 

exec/make_app_from_files.R
When relating stats to assays, pick the last one by default.
=> Pick last assay for stats by default

R/accessory.R, exec/make_app_from_files.R, man/compile_contrast_data.Rd
Remove relics of the need for explicit separator specification (now inferred from file extension).
=> Remove explicit separator specifications

exec/differential_plots.R
Currently the differential plotting script assumes fold changes in input tables are pre-logged, which is inconsistent with its treatment of p values. So let's switch the assumption to unlogged.
=> Don't assume fold change values are already logged in differential plots

exec/validate_fom_components.R
This change prevents contrasts re-written with use of the validate script being given NA values in the blocking column, which can disrupt workflows.
=> Don't write NA values in contrasts as NAs

R/boxplot.R, R/heatmap.R, R/rnaseq.R, man/ggplot_boxplot.Rd, man/ggplot_densityplot.Rd
This PR makes some changes to allow more control over font sizing in boxplots etc, by providing an interface to ggplot `base_size`.
=> Paramterise font size, improve facet label in ggplot boxplot

exec/differential_plots.R
Static differential plots currently look like:
... because the fold change threshold hasn't been with the plot values. This is the fix
=> log differential fc threshold

R/boxplot.R, R/colormaker.R, R/dendro.R, exec/differential_plots.R, exec/exploratory_plots.R, man/makeColorScale.Rd
This PR removes some assumptions on group numbers for palette generation in the exec scripts, which were hanging over from testing, and actually fixes routines so no explicit palette specification is required in most cases.
=> Centralise default palette generation, fix issues

R/colormaker.R, R/scatterplot.R
This PR just addresses a lingering issue carried over from the last PR. Some form of palette needs to be generated for scatterplots even without multiple classes of point, which this ensures.
=> Final palette fixes

R/accessory.R, exec/make_app_from_files.R
This PR:
- Adds a separate field to use for feature ID in the differential files (can't be assumed to be the same as the one in the matrix file).
- Wires in the description fields so they will actually work.
=> App separate feature ID for differential files

R/accessory.R, exec/make_app_from_files.R, man/eselistfromConfig.Rd, man/read_matrix.Rd
This PR allows the read_matrix function to guess and reverse log status at object creation. This assists in the consistent display of expression values from different assays when multiple such are provided by pipelines.
=> Guess unlog

.github/workflows/check-release.yaml, R/ExploratorySummarizedExperiment-class.R, R/ExploratorySummarizedExperimentList-class.R, R/accessory.R, R/contrasts.R, R/experimenttable.R, R/heatmap.R, R/sampleselect.R, R/scatterplot.R, R/selectmatrix.R, man/sampleselect.Rd, man/selectmatrix.Rd
In this PR:
- Remove internal assumptions on structure of contrasts, allowing for contrasts with the same variable and groups, but different blocking variables, for example.
Plus fixes for issues reported by @WackerO:
- colorBy error in loading plots (the loading plots don't require coloring)
- wire in currently disconnected point size controls
- remove generic matrix controls not relevant in metadata/ PCA plot and which were leading to errors (means, metadata selection)
- set `check.names = FALSE` in various places, to prevent mangling of space-containing sample covariates
- turn off erroring for warnings in CI so we don't get the constant issue surrounding the number of imports
=> Better contrasts, miscellaneous bugs

exec/exploratory_plots.R
This PR adds `na.omit` to `exploratory_plots.R` to allow inputting matrices with NA values without producing an error
=> Added na.omit to matrix reading in exploratory_plots.R

exec/make_app_from_files.R
This PR fixes the following error:
```
Command error:
[1] "Updating BioC packages as will be required for shinyapps.io deployment"
Error: Bioconductor version '3.16' requires R version '4.2'; use `version = '3.17'`
with R version 4.3; see https://bioconductor.org/install
Execution halted
```
=> Remove BioC versions

R/accessory.R, R/boxplot.R, exec/exploratory_plots.R
Making a couple of fixes here:
- In the exploratory plotting function, exclude any samples without a value in the key plotting variable.
- Reduce the granularity of the density calculation to try and improve performance.
- Don't mix samples in the density plot- we were getting spikiness due to conflated samples, which is clearly not desirable.
=> Density fixes

R/accessory.R
ATM, a call to `prettifyVariablename` is missing in `validate_indices` while `stringsToNamedVector` contains a prettify. This leads to `exploratory_plots.R` throwing an `error Invalid` assays because it will e.g. compare the strings `raw` and `Raw`. This PR adds the prettify to fix this issue.
=> Add prettify to validate_indices

R/accessory.R, exec/exploratory_plots.R, man/cond_log2_transform_assays.Rd, man/shinyngs.Rd, man/validate_indices.Rd
One final fix after last couple of PRs- keep things unprettified during log handling.
=> Disable prettifification in log check

DESCRIPTION
The devtools/remotes packages use the default repositories when using install_github.
The shinyngs package depends on limma and GSEABase, which are Bioconductor packages.
The devtools/remotes packages can add the corresponding bioconductor repositories to fetch those dependencies as well, but they need to know if the package has bioconductor dependencies.
How do they figure that out?
They check if there is a biocview assigned to the package:
https://github.com/r-lib/remotes/blob/828ba533af96fffbefeb0f9559329cc1da1242e8/R/deps.R#L137
https://github.com/r-lib/remotes/blob/828ba533af96fffbefeb0f9559329cc1da1242e8/install-github.R#L6095
This PR adds a generic biocviews to the description. It does not harm and it helps the remotes package to figure out that it has to add the bioconductor …
=> Fix installation through remotes/devtools

.github/workflows/release-wasm.yml
This PR adds WebAssembly support to the shinyngs package, enabling it to work with shinylive for browser-based execution.
- Added `.github/workflows/release-wasm.yml` workflow that:
- Builds the package and dependencies for WebAssembly
- Creates a file system image containing the R package library
- Attaches WebAssembly assets to GitHub releases
Currently, when using shinyngs with shinylive, the following error occurs:
```
rror in `get_github_wasm_assets()`:
! Can't find WebAssembly binary assets for github::pinin4fjords/shinyngs@v2.2.0
! Ensure WebAssembly binary assets are associated with the GitHub release "v2.2.0".
ℹ WebAssembly binary assets can be built on release using GitHub Actions: <https://github.com/r-wasm/actions>
ℹ Alternatively, install a CRAN version of this package to use …
```
=> Add WebAssembly support workflow for shinylive compatibility

.github/workflows/check-release.yaml, README.md
Something to do with the object handling in R 4.5 is breaking things with the classes defined here. Pin the R back for now.
=> Fix CI issues by pinning R version

R/accessory.R
Two changes are introduced here:
1. Support literal strings for `limma::makeContrasts`
2. Minor changes to how blocking variables are obtained with `setdiff` as the previous method would crash if the formula contained a 0.
=> Support literal strings for `limma::makeContrasts`
